# Etapa 1 - build
FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /app
COPY src .

RUN mvn clean package -DskipTests

# Etapa 2 - execução
FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]