spring.application.name=AtividadeSpringBoot

# Configuração do banco H2 em memória
spring.datasource.url=jdbc:h2:mem:atividadesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialeto do Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Cria/atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Habilita o console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console